### ISSUE TITLE
Double intersection

### ISSUE THREAD

**Issue by tuansyle** [TUW-GEO/pytileproj#12]
In base.py, line 365. Is it correct to use double intersection? I think it should be 
        intersect = geom.Intersection(subgrid.polygon_proj)
instead of 
        intersect = geom.Intersection(geom.Intersection(subgrid.polygon_geog))
Otherwise, ascat2equi7 will not working properly

**Comment by bbauerma** [comment]
is corrected and solved by commit #5aa70e76abff9b9da30a449f4be5219c57eb5f2a
