### ISSUE TITLE
ASCAT2equi7 failed due to a new check in pytileproj

### ISSUE THREAD

**Issue by tuansyle** [TUW-GEO/pytileproj#16]
https://github.com/TUW-GEO/pytileproj/blob/5bce5d515045413ffd92df12c24531e123945dd1/pytileproj/base.py#L328

Could you please check what kind of check it is?

**Comment by sebhahn** [comment]
What is the error message?

**Comment by bbauerma** [comment]
this is the conversion of lat lon coords to equi7 coords. 

in _lonlat2xy_subgrid() it checks if the lat lon coords lies within the subgrid (continent)

if you don't know the continent, you use lonlat2xy()

i never had problems with this function.
