### ISSUE TITLE
Python 3 travis build fails

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/pytileproj#9]
Seems like an issue (or version conflict) with astropy.

Copied from travis:
`pkg_resources.VersionConflict: (astropy 1.3 (/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages), Requirement.parse('astropy>=2.0.1'))`

**Comment by bbauerma** [comment]
...so?

Was schlagst vor? ;-)

PS: Rohrbruch behoben!
